name: Assignment Checking

on:
  push:
    branches:
      - setup-actions
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check branch name
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.event.pull_request.head.repo.full_name }}"
          echo "${{ github.event.pull_request.head.ref }}"
          echo "${{ github.event.pull_request.head.ref_name }}"

